/* festival.js — Guild Festival dashboard
 *
 * Data source: ./data/festival.json
 * Structure (generated by publish_website.py):
 * [
 *   {
 *     "date": "2026-03-30",
 *     "filename": "...",
 *     "summary": { "total_players": N, "completed_bonus": N, "total_score": N },
 *     "players": [ { "name", "score", "completed", "total", "bonus" }, ... ]
 *   },
 *   ...
 * ]
 */

const FESTIVAL_MIN = 3100;
const DATA_URL     = './data/festival.json';

// Chart.js defaults
Chart.defaults.color           = '#8b949e';
Chart.defaults.borderColor     = '#30363d';
Chart.defaults.font.family     = "-apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif";

// ── State ───────────────────────────────────────────────────────────────────
let festivals    = [];   // sorted oldest → newest
let activeTab    = 'history';
let selectedFest = null; // currently drilled-in festival
let chartHistLine, chartHistBar, chartMemberLine, chartMemberBar;

// ── Utilities ────────────────────────────────────────────────────────────────

const fmtNum = n => (n >= 1_000_000 ? (n/1_000_000).toFixed(1)+'M'
                   : n >= 1_000     ? (n/1_000).toFixed(1)+'K'
                   : String(n));

const fmtComma = n => Number(n).toLocaleString(window.i18n?.currentLang || 'en');

const shortDate = d => {
  try {
    const dt = new Date(d + 'T00:00:00');
    return dt.toLocaleDateString(window.i18n?.currentLang || 'en', {month:'short', day:'numeric'});
  } catch { return d.slice(5,10); }
};

const fullDate = d => {
  try {
    const dt = new Date(d + 'T00:00:00');
    return dt.toLocaleDateString(window.i18n?.currentLang || 'en', {year:'numeric', month:'long', day:'numeric'});
  } catch { return d; }
};

function destroyChart(c) { if (c) { try { c.destroy(); } catch {} } }

// ── Fetch ────────────────────────────────────────────────────────────────────

async function loadData() {
  const resp = await fetch(DATA_URL + '?v=' + Date.now());
  if (!resp.ok) throw new Error(`HTTP ${resp.status}`);
  return resp.json();
}

// ── Init ─────────────────────────────────────────────────────────────────────

async function init() {
  try {
    const raw = await loadData();
    // Sort oldest → newest
    festivals = [...raw].sort((a, b) => (a.date > b.date ? 1 : -1));
    renderHistoryTab();
  } catch (err) {
    document.getElementById('festival-list').innerHTML =
      `<div class="error-state">⚠️ ${t('error_loading')}: ${err.message}</div>`;
  }
}

document.addEventListener('DOMContentLoaded', () => {
  if (window.location.pathname.split('/').pop() !== 'festival.html') return;
  // Wait for i18n to be ready before first render
  const checkI18n = setInterval(() => {
    if (window.i18n && Object.keys(window.i18n.data).length > 0) {
      clearInterval(checkI18n);
      init();
    }
  }, 50);

  // Re-render when language changes
  window.addEventListener('languageChanged', () => {
    if (activeTab === 'history') renderHistoryTab();
    else if (activeTab === 'tasks') initTasks();
  });
});

// ── TAB SWITCHING ─────────────────────────────────────────────────────────────

document.querySelectorAll('.tab-btn').forEach(btn => {
  btn.addEventListener('click', () => {
    const tab = btn.dataset.tab;
    document.querySelectorAll('.tab-btn').forEach(b => b.classList.remove('active'));
    btn.classList.add('active');
    document.getElementById('tab-history-content').style.display  = tab === 'history'  ? '' : 'none';
    document.getElementById('tab-tasks-content').style.display    = tab === 'tasks'    ? '' : 'none';
    activeTab = tab;
    if (tab === 'tasks' && !window._tasksLoaded) { window._tasksLoaded = true; initTasks(); }
  });
});

// ── HISTORY TAB ──────────────────────────────────────────────────────────────


function renderHistoryTab() {
  if (!festivals.length) {
    document.getElementById('festival-list').innerHTML =
      `<div class="empty-state"><div class="empty-icon">🎪</div><h3>${t('no_fest_data')}</h3></div>`;
    return;
  }

  let sumAvgScore = 0; let sumPass = 0; let sumFail = 0; let sumBonus = 0;
  festivals.forEach(f => {
     const pLen = f.summary.total_players || 1;
     sumAvgScore += Math.round(f.summary.total_score / pLen);
     sumPass += f.summary.passed_min;
     sumFail += f.summary.failed_min;
     sumBonus += f.summary.completed_bonus || 0;
  });
  const n = festivals.length;
  document.getElementById('stat-festivals').textContent    = n;
  document.getElementById('stat-avg-score').textContent    = fmtNum(Math.round(sumAvgScore / n));
  document.getElementById('stat-avg-pass').textContent     = Math.round(sumPass / n);
  document.getElementById('stat-avg-fail').textContent     = Math.round(sumFail / n);
  document.getElementById('stat-avg-bonus').textContent    = Math.round(sumBonus / n);
  document.getElementById('festival-count-badge').textContent = `${n} ${t('events_count')}`;

  buildHistoryCharts();
  renderFestivalList(festivals);
}

function renderFestivalList(list) {
  const el = document.getElementById('festival-list');
  if (!list.length) {
    el.innerHTML = `<div class="empty-state"><div class="empty-icon">🔍</div><h3>${t('no_results')}</h3></div>`;
    return;
  }

  // Render newest first in the card list
  const sorted = [...list].reverse();

  el.innerHTML = `<div class="session-list" style="padding:1.5rem">` +
    sorted.map((f, i) => {
      const s       = f.summary;
      const players = f.players || [];
      const passed  = players.filter(p => p.score >= FESTIVAL_MIN).length;
      const pct     = players.length ? Math.round(passed / players.length * 100) : 0;
      const isLatest = f === festivals[festivals.length - 1];

      return `
      <div class="session-card" data-date="${f.date}" onclick="openFestivalDetail('${f.date}')">
        <div class="session-title">
          🎪 ${fullDate(f.date)}
          ${isLatest ? `<span class="badge" style="font-size:0.7rem;background:rgba(168,85,247,.15);color:#a855f7;border-color:rgba(168,85,247,.3)">${t('latest')}</span>` : ''}
        </div>
        <div class="session-meta">
          <div class="session-row">
            <span>🏆 ${t('total_score')}</span>
            <span class="val">${fmtNum(s.total_score)}</span>
          </div>
          <div class="session-row">
            <span>👥 ${t('players')}</span>
            <span class="val">${s.total_players}</span>
          </div>
          <div class="session-row">
            <span>✅ ${t('bonus_completed')}</span>
            <span class="val">${s.completed_bonus}</span>
          </div>
          <div class="session-row" style="margin-top:4px">
            <span>${t('min_met')} (≥${fmtComma(FESTIVAL_MIN)})</span>
            <span class="val" style="color:${pct>=80?'var(--festival-pass)':pct>=50?'var(--accent-yellow)':'var(--festival-fail)'}">${passed}/${s.total_players} (${pct}%)</span>
          </div>
          <div class="pass-bar-wrap" style="margin-top:6px">
            <div class="pass-bar-track" style="flex:1">
              <div class="pass-bar-fill" style="width:${pct}%"></div>
            </div>
            <span style="color:var(--text-muted);font-size:0.78rem;min-width:34px">${pct}%</span>
          </div>
        </div>
        <div class="view-btn">${t('view_details')}</div>
      </div>`;
    }).join('') + '</div>';
}

// Search filter
document.getElementById('search-festival').addEventListener('input', e => {
  const q = e.target.value.toLowerCase().trim();
  const filtered = q ? festivals.filter(f => f.date.includes(q) || shortDate(f.date).toLowerCase().includes(q)) : festivals;
  renderFestivalList(filtered);
});

// ── FESTIVAL DETAIL ───────────────────────────────────────────────────────────

function openFestivalDetail(date) {
  const f = festivals.find(x => x.date === date);
  if (!f) return;
  selectedFest = f;

  document.getElementById('festival-list').style.display    = 'none';
  document.getElementById('festival-detail').style.display  = '';
  document.getElementById('search-festival').parentElement.parentElement.style.display = 'none';
  // Hide chart cards while in detail
  document.querySelectorAll('#tab-history-content .card:not(#festival-detail .card)').forEach(c => c.style.display='none');
  document.getElementById('festival-stats').style.display   = 'none';

  const s       = f.summary;
  const players = [...(f.players || [])].sort((a, b) => b.score - a.score);
  const passed  = players.filter(p => p.score >= FESTIVAL_MIN).length;
  const pct     = players.length ? Math.round(passed / players.length * 100) : 0;

  document.getElementById('detail-title').textContent = fullDate(f.date);

  // Detail summary box
  document.getElementById('detail-summary-box').innerHTML = `
    <h2>${fullDate(f.date)}</h2>
    <div class="festival-score-big">${fmtNum(s.total_score)}</div>
    <div class="meta-row" style="margin-top:0.8rem">
      <div class="meta-item">👥 <strong>${s.total_players}</strong> ${t('players')}</div>
      <div class="meta-item">✅ ${t('bonus')}: <strong>${s.completed_bonus}</strong></div>
      <div class="meta-item met-yes">✔ ${t('min_met')}: <strong>${passed} (${pct}%)</strong></div>
      <div class="meta-item met-no">✖ ${t('miss')}: <strong>${players.length - passed}</strong></div>
    </div>
    <div class="pass-bar-wrap" style="margin-top:10px">
      <span style="font-size:0.8rem;color:var(--text-muted)">${t('min_compliance')}</span>
      <div class="pass-bar-track" style="flex:1">
        <div class="pass-bar-fill" style="width:${pct}%"></div>
      </div>
      <span style="font-size:0.8rem;color:var(--text-muted)">${pct}%</span>
    </div>`;

  renderDetailTable(players);

  document.getElementById('search-detail').addEventListener('input', e => {
    const q = e.target.value.toLowerCase();
    renderDetailTable(q ? players.filter(p => p.name.toLowerCase().includes(q)) : players);
  });
}

function renderDetailTable(players) {
  const best = players.length ? Math.max(...players.map(p => p.score)) : 0;
  const tbody = document.getElementById('detail-tbody');
  tbody.innerHTML = players.map((p, i) => {
    const met   = p.score >= FESTIVAL_MIN;
    const isBest = p.score === best && best > 0;
    const cls   = isBest ? 'row-best' : (met ? 'row-pass' : 'row-fail');
    return `<tr class="${cls}">
      <td class="center" data-label="#">${i+1}</td>
      <td data-label="${t('table_player')}">${isBest ? '🥇 ' : ''}${p.name}</td>
      <td class="right" data-label="${t('score')}"><strong>${fmtNum(p.score)}</strong></td>
      <td class="center ${met?'met-yes':'met-no'}" data-label="${t('table_status')}">${met ? t('met_yes') : t('met_no')}</td>
      <td class="center" data-label="${t('bonus_completed')}">${p.completed}/${p.total}</td>
      <td class="center ${p.bonus?'met-yes':''}" data-label="${t('bonus')}">${p.bonus ? '✅' : '—'}</td>
    </tr>`;
  }).join('');
}

// Back button
document.getElementById('back-to-list').addEventListener('click', e => {
  e.preventDefault();
  document.getElementById('festival-list').style.display    = '';
  document.getElementById('festival-detail').style.display  = 'none';
  document.getElementById('search-festival').parentElement.parentElement.style.display = '';
  document.querySelectorAll('#tab-history-content .card').forEach(c => c.style.display='');
  document.getElementById('festival-stats').style.display   = '';
  selectedFest = null;
});


// ── HISTORY CHARTS ────────────────────────────────────────────────────────────
function buildHistoryCharts() {
  destroyChart(chartHistLine);
  destroyChart(chartHistBar);

  const labels    = festivals.map(f => shortDate(f.date));
  const avgScores = festivals.map(f => Math.round(f.summary.total_score / (f.summary.total_players || 1)));
  const passed    = festivals.map(f => f.summary.passed_min        || 0);
  const failed    = festivals.map(f => f.summary.failed_min        || 0);
  const bonus     = festivals.map(f => f.summary.completed_bonus   || 0);

  const _tip = {
    backgroundColor: 'rgba(13,17,23,.95)',
    titleColor: '#c9d1d9', bodyColor: '#c9d1d9',
    borderColor: '#30363d', borderWidth: 1
  };
  const _legend = { position: 'top', labels: { usePointStyle: true, boxWidth: 10, color: 'rgba(255,255,255,0.7)', padding: 14 } };
  const _ptStyle = (color) => ({ pointRadius: 5, pointBackgroundColor: '#0d1117', pointBorderColor: color, pointBorderWidth: 2 });

  // ── Compliance line chart (3 toggle-able lines) ─────────────────────────────
  const ctxBar = document.getElementById('chart-history-bar').getContext('2d');
  chartHistBar = new Chart(ctxBar, {
    type: 'line',
    data: {
      labels,
      datasets: [
        { label: t('fest_part_completed'),   data: passed, borderColor: '#22c55e', backgroundColor: 'rgba(34,197,94,0.08)',   borderWidth: 2.5, tension: 0.3, fill: false, ..._ptStyle('#22c55e') },
        { label: t('fest_part_failed'),   data: failed, borderColor: '#ef4444', backgroundColor: 'rgba(239,68,68,0.08)',   borderWidth: 2.5, tension: 0.3, fill: false, ..._ptStyle('#ef4444') },
        { label: t('fest_bonus_earned'), data: bonus,  borderColor: '#a855f7', backgroundColor: 'rgba(168,85,247,0.08)',  borderWidth: 2.5, tension: 0.3, fill: false, borderDash: [5,3], ..._ptStyle('#a855f7') }
      ]
    },
    options: {
      responsive: true, maintainAspectRatio: false,
      interaction: { mode: 'index', intersect: false },
      plugins: { legend: _legend, tooltip: _tip },
      scales: {
        x: { grid: { display: false } },
        y: { grid: { color: 'rgba(255,255,255,0.05)' }, title: { display: true, text: t('players'), color: 'rgba(255,255,255,0.5)' }, beginAtZero: true }
      }
    }
  });

  // ── Average points line chart ────────────────────────────────────────────────
  const ctxLine = document.getElementById('chart-history-line').getContext('2d');
  chartHistLine = new Chart(ctxLine, {
    type: 'line',
    data: {
      labels,
      datasets: [{
        label: t('avg_pts_player_ax'),
        data: avgScores,
        borderColor: '#f59e0b',
        backgroundColor: festivals.length === 1 ? 'rgba(245,158,11,0.7)' : 'rgba(245,158,11,0.12)',
        borderWidth: 2.5, tension: 0.3,
        fill: true,
        ..._ptStyle('#f59e0b')
      }]
    },
    options: {
      responsive: true, maintainAspectRatio: false,
      interaction: { mode: 'index', intersect: false },
      plugins: {
        legend: { position: 'top', labels: { usePointStyle: true, boxWidth: 10, color: 'rgba(255,255,255,0.7)' } },
        tooltip: _tip
      },
      scales: {
        x: { grid: { display: false } },
        y: { grid: { color: 'rgba(255,255,255,0.05)' }, title: { display: true, text: t('avg_pts_player_ax'), color: 'rgba(255,255,255,0.5)' }, beginAtZero: false }
      }
    }
  });
}

// ── Start ─────────────────────────────────────────────────────────────────────
// init() called by DOMContentLoaded above

// Re-render when language changes
window.addEventListener('languageChanged', () => {
  if (selectedFest) {
    openFestivalDetail(selectedFest.date);
  } else {
    renderHistoryTab();
  }
});

// ── TASKS LOGIC (Merged) ─────────────────────────────────────────────────────
async function initTasks() {
  const container = document.getElementById('tasks-container');
  if (!container) return;
  const oldHTML = container.innerHTML;
  container.innerHTML = `<div class="loading-state"><div class="spinner"></div><p>${t('loading_missions')}</p></div>`;

  try {
    const resp = await fetch('./data/tasks.json?v=' + Date.now());
    if (!resp.ok) throw new Error(`HTTP ${resp.status}`);
    const tasks = await resp.json();
    
    const t200 = tasks['200_percent_bonus_missions'] || [];
    const t120 = tasks['120_percent_bonus_missions'] || [];
    
    container.innerHTML = `
      <div class="stats-grid" style="margin-bottom:1.5rem;">
        <div class="stat-card orange">
          <div class="stat-icon">🔥</div>
          <div class="stat-value">${t200.length}</div>
          <div class="stat-label">${t('bonus_missions_200')}</div>
        </div>
        <div class="stat-card blue">
          <div class="stat-icon">🌟</div>
          <div class="stat-value">${t120.length}</div>
          <div class="stat-label">${t('bonus_missions_120')}</div>
        </div>
        <div class="stat-card green">
          <div class="stat-icon">🎯</div>
          <div class="stat-value">${t200.length + t120.length}</div>
          <div class="stat-label">${t('total_missions_tracked')}</div>
        </div>
      </div>
      
      <div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:1rem;">
        ${renderTaskTable(t('bonus_missions_200_title'), t200, 'orange')}
        ${renderTaskTable(t('bonus_missions_120_title'), t120, 'blue')}
      </div>
    `;
  } catch (err) {
    container.innerHTML = oldHTML; // restore loading or something
    container.innerHTML = `<div class="error-state">⚠️ ${t('error_loading')}. ${err.message}</div>`;
  }
}

function renderTaskTable(title, tasksList, colorClass) {
  if (!tasksList.length) {
    return `
      <div class="card">
        <div class="card-header"><h2>${title}</h2></div>
        <div class="empty-state" style="padding:2rem;"><p>${t('missions_tier_empty')}</p></div>
      </div>
    `;
  }
  
  return `
    <div class="card" style="border-top:3px solid var(--accent-${colorClass});">
      <div class="card-header">
        <h2>${title}</h2>
        <span class="badge-count">${tasksList.length}</span>
      </div>
      <div class="table-wrapper">
        <table style="font-size:0.9rem;">
          <thead>
            <tr>
              <th class="right" style="width:70px;">${t('points')}</th>
              <th>${t('mission')}</th>
              <th>${t('qty_time_limit')}</th>
            </tr>
          </thead>
          <tbody>
            ${tasksList.map(task => `
              <tr style="transition:background 0.15s;" onmouseover="this.style.background='var(--bg-hover)'" onmouseout="this.style.background=''">
                <td class="right mono" data-label="${t('points')}" style="font-weight:700;color:var(--accent-${colorClass});font-size:0.95rem;">${task.required_points}</td>
                <td class="card-main" data-label="${t('mission')}" style="font-weight:600;color:var(--text-primary);">${task.mission}</td>
                <td data-label="${t('qty_time_limit')}">
                  <div style="color:var(--text-secondary);font-weight:500;">${task.quantity}</div>
                  <div style="color:var(--text-muted);font-size:0.8rem;margin-top:2px;">⏳ ${task.time_limit}</div>
                </td>
              </tr>
            `).join('')}
          </tbody>
        </table>
      </div>
    </div>
  `;
}
