/* festival.js — Guild Festival dashboard
 *
 * Data source: ./data/festival.json
 * Structure (generated by publish_website.py):
 * [
 *   {
 *     "date": "2026-03-30",
 *     "filename": "...",
 *     "summary": { "total_players": N, "completed_bonus": N, "total_score": N },
 *     "players": [ { "name", "score", "completed", "total", "bonus" }, ... ]
 *   },
 *   ...
 * ]
 */

const FESTIVAL_MIN = 3100;
const DATA_URL     = './data/festival.json';

// Chart.js defaults
Chart.defaults.color           = '#8b949e';
Chart.defaults.borderColor     = '#30363d';
Chart.defaults.font.family     = "-apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif";

// ── State ───────────────────────────────────────────────────────────────────
let festivals    = [];   // sorted oldest → newest
let activeTab    = 'history';
let selectedFest = null; // currently drilled-in festival
let chartHistLine, chartHistBar, chartMemberLine, chartMemberBar;

// ── Utilities ────────────────────────────────────────────────────────────────

const fmtNum = n => (n >= 1_000_000 ? (n/1_000_000).toFixed(1)+'M'
                   : n >= 1_000     ? (n/1_000).toFixed(1)+'K'
                   : String(n));

const fmtComma = n => Number(n).toLocaleString('en-US');

const shortDate = d => {
  try {
    const dt = new Date(d + 'T00:00:00');
    return dt.toLocaleDateString('en-US', {month:'short', day:'numeric'});
  } catch { return d.slice(5,10); }
};

const fullDate = d => {
  try {
    const dt = new Date(d + 'T00:00:00');
    return dt.toLocaleDateString('en-US', {year:'numeric', month:'long', day:'numeric'});
  } catch { return d; }
};

function destroyChart(c) { if (c) { try { c.destroy(); } catch {} } }

// ── Fetch ────────────────────────────────────────────────────────────────────

async function loadData() {
  const resp = await fetch(DATA_URL + '?v=' + Date.now());
  if (!resp.ok) throw new Error(`HTTP ${resp.status}`);
  return resp.json();
}

// ── Init ─────────────────────────────────────────────────────────────────────

async function init() {
  try {
    const raw = await loadData();
    // Sort oldest → newest
    festivals = [...raw].sort((a, b) => (a.date > b.date ? 1 : -1));
    renderHistoryTab();
    renderMembersTab();
  } catch (err) {
    document.getElementById('festival-list').innerHTML =
      `<div class="error-state">⚠️ Could not load festival data: ${err.message}</div>`;
  }
}

// ── TAB SWITCHING ─────────────────────────────────────────────────────────────

document.querySelectorAll('.tab-btn').forEach(btn => {
  btn.addEventListener('click', () => {
    const tab = btn.dataset.tab;
    document.querySelectorAll('.tab-btn').forEach(b => b.classList.remove('active'));
    btn.classList.add('active');
    document.getElementById('tab-history-content').style.display  = tab === 'history'  ? '' : 'none';
    document.getElementById('tab-members-content').style.display  = tab === 'members'  ? '' : 'none';
    activeTab = tab;
  });
});

// ── HISTORY TAB ──────────────────────────────────────────────────────────────

function renderHistoryTab() {
  if (!festivals.length) {
    document.getElementById('festival-list').innerHTML =
      `<div class="empty-state">
        <div class="empty-icon">🎪</div>
        <h3>No festival data yet</h3>
        <p>Upload a GUILD_FESTIVAL Excel via the Telegram bot.</p>
       </div>`;
    return;
  }

  // Stat cards
  const latest   = festivals[festivals.length - 1];
  const players  = latest.players || [];
  const passed   = players.filter(p => p.score >= FESTIVAL_MIN).length;
  const failed   = players.length - passed;

  document.getElementById('stat-festivals').textContent    = festivals.length;
  document.getElementById('stat-latest-score').textContent = fmtNum(latest.summary.total_score);
  document.getElementById('stat-passed').textContent       = passed;
  document.getElementById('stat-failed').textContent       = failed;
  document.getElementById('festival-count-badge').textContent = `${festivals.length} event(s)`;

  // Charts
  buildHistoryLineChart();
  buildHistoryBarChart();

  // Festival list
  renderFestivalList(festivals);
}

function renderFestivalList(list) {
  const el = document.getElementById('festival-list');
  if (!list.length) {
    el.innerHTML = '<div class="empty-state"><div class="empty-icon">🔍</div><h3>No results</h3></div>';
    return;
  }

  // Render newest first in the card list
  const sorted = [...list].reverse();

  el.innerHTML = `<div class="session-list" style="padding:1.5rem">` +
    sorted.map((f, i) => {
      const s       = f.summary;
      const players = f.players || [];
      const passed  = players.filter(p => p.score >= FESTIVAL_MIN).length;
      const pct     = players.length ? Math.round(passed / players.length * 100) : 0;
      const isLatest = f === festivals[festivals.length - 1];

      return `
      <div class="session-card" data-date="${f.date}" onclick="openFestivalDetail('${f.date}')">
        <div class="session-title">
          🎪 ${fullDate(f.date)}
          ${isLatest ? '<span class="badge" style="font-size:0.7rem;background:rgba(168,85,247,.15);color:#a855f7;border-color:rgba(168,85,247,.3)">Latest</span>' : ''}
        </div>
        <div class="session-meta">
          <div class="session-row">
            <span>🏆 Total Score</span>
            <span class="val">${fmtComma(s.total_score)}</span>
          </div>
          <div class="session-row">
            <span>👥 Players</span>
            <span class="val">${s.total_players}</span>
          </div>
          <div class="session-row">
            <span>✅ Bonus Completed</span>
            <span class="val">${s.completed_bonus}</span>
          </div>
          <div class="session-row" style="margin-top:4px">
            <span>Min. Met (≥${fmtComma(FESTIVAL_MIN)})</span>
            <span class="val" style="color:${pct>=80?'var(--festival-pass)':pct>=50?'var(--accent-yellow)':'var(--festival-fail)'}">${passed}/${s.total_players} (${pct}%)</span>
          </div>
          <div class="pass-bar-wrap" style="margin-top:6px">
            <div class="pass-bar-track" style="flex:1">
              <div class="pass-bar-fill" style="width:${pct}%"></div>
            </div>
            <span style="color:var(--text-muted);font-size:0.78rem;min-width:34px">${pct}%</span>
          </div>
        </div>
        <div class="view-btn">View Details →</div>
      </div>`;
    }).join('') + '</div>';
}

// Search filter
document.getElementById('search-festival').addEventListener('input', e => {
  const q = e.target.value.toLowerCase().trim();
  const filtered = q ? festivals.filter(f => f.date.includes(q) || shortDate(f.date).toLowerCase().includes(q)) : festivals;
  renderFestivalList(filtered);
});

// ── FESTIVAL DETAIL ───────────────────────────────────────────────────────────

function openFestivalDetail(date) {
  const f = festivals.find(x => x.date === date);
  if (!f) return;
  selectedFest = f;

  document.getElementById('festival-list').style.display    = 'none';
  document.getElementById('festival-detail').style.display  = '';
  document.getElementById('search-festival').parentElement.parentElement.style.display = 'none';
  // Hide chart cards while in detail
  document.querySelectorAll('#tab-history-content .card:not(#festival-detail .card)').forEach(c => c.style.display='none');
  document.getElementById('festival-stats').style.display   = 'none';

  const s       = f.summary;
  const players = [...(f.players || [])].sort((a, b) => b.score - a.score);
  const passed  = players.filter(p => p.score >= FESTIVAL_MIN).length;
  const pct     = players.length ? Math.round(passed / players.length * 100) : 0;

  document.getElementById('detail-title').textContent = fullDate(f.date);

  // Detail summary box
  document.getElementById('detail-summary-box').innerHTML = `
    <h2>${fullDate(f.date)}</h2>
    <div class="festival-score-big">${fmtComma(s.total_score)}</div>
    <div class="meta-row" style="margin-top:0.8rem">
      <div class="meta-item">👥 <strong>${s.total_players}</strong> players</div>
      <div class="meta-item">✅ Bonus: <strong>${s.completed_bonus}</strong></div>
      <div class="meta-item met-yes">✔ Passed min: <strong>${passed} (${pct}%)</strong></div>
      <div class="meta-item met-no">✖ Below min: <strong>${players.length - passed}</strong></div>
    </div>
    <div class="pass-bar-wrap" style="margin-top:10px">
      <span style="font-size:0.8rem;color:var(--text-muted)">Min. Compliance</span>
      <div class="pass-bar-track" style="flex:1">
        <div class="pass-bar-fill" style="width:${pct}%"></div>
      </div>
      <span style="font-size:0.8rem;color:var(--text-muted)">${pct}%</span>
    </div>`;

  renderDetailTable(players);

  document.getElementById('search-detail').addEventListener('input', e => {
    const q = e.target.value.toLowerCase();
    renderDetailTable(q ? players.filter(p => p.name.toLowerCase().includes(q)) : players);
  });
}

function renderDetailTable(players) {
  const best = players.length ? Math.max(...players.map(p => p.score)) : 0;
  const tbody = document.getElementById('detail-tbody');
  tbody.innerHTML = players.map((p, i) => {
    const met   = p.score >= FESTIVAL_MIN;
    const isBest = p.score === best && best > 0;
    const cls   = isBest ? 'row-best' : (met ? 'row-pass' : 'row-fail');
    return `<tr class="${cls}">
      <td class="center">${i+1}</td>
      <td>${isBest ? '🥇 ' : ''}${p.name}</td>
      <td class="right"><strong>${fmtComma(p.score)}</strong></td>
      <td class="center ${met?'met-yes':'met-no'}">${met ? '✅ YES' : '❌ NO'}</td>
      <td class="center">${p.completed}/${p.total}</td>
      <td class="center">${p.bonus ? '✅' : '—'}</td>
    </tr>`;
  }).join('');
}

// Back button
document.getElementById('back-to-list').addEventListener('click', e => {
  e.preventDefault();
  document.getElementById('festival-list').style.display    = '';
  document.getElementById('festival-detail').style.display  = 'none';
  document.getElementById('search-festival').parentElement.parentElement.style.display = '';
  document.querySelectorAll('#tab-history-content .card').forEach(c => c.style.display='');
  document.getElementById('festival-stats').style.display   = '';
  selectedFest = null;
});

// ── HISTORY CHARTS ────────────────────────────────────────────────────────────

function buildHistoryLineChart() {
  destroyChart(chartHistLine);
  const labels = festivals.map(f => shortDate(f.date));
  const scores = festivals.map(f => f.summary.total_score);

  const ctx = document.getElementById('chart-history-line').getContext('2d');
  chartHistLine = new Chart(ctx, {
    type: 'line',
    data: {
      labels,
      datasets: [{
        label: 'Total Score',
        data: scores,
        borderColor: '#a855f7',
        backgroundColor: 'rgba(168,85,247,0.12)',
        pointBackgroundColor: scores.map((s, i) =>
          i === scores.length - 1 ? '#f59e0b' : '#a855f7'),
        pointRadius: 6,
        tension: 0.35,
        fill: true,
      }]
    },
    options: {
      responsive: true,
      interaction: { mode: 'index', intersect: false },
      plugins: {
        legend: { display: false },
        tooltip: {
          callbacks: {
            label: ctx => ` Score: ${fmtComma(ctx.raw)}`
          }
        }
      },
      scales: {
        y: {
          grid: { color: 'rgba(255,255,255,0.05)' },
          ticks: { callback: v => fmtNum(v) }
        },
        x: { grid: { color: 'rgba(255,255,255,0.04)' } }
      }
    }
  });
}

function buildHistoryBarChart() {
  destroyChart(chartHistBar);
  const labels = festivals.map(f => shortDate(f.date));
  const scores = festivals.map(f => f.summary.total_score);

  const ctx = document.getElementById('chart-history-bar').getContext('2d');
  chartHistBar = new Chart(ctx, {
    type: 'bar',
    data: {
      labels,
      datasets: [{
        label: 'Total Score',
        data: scores,
        backgroundColor: scores.map((_, i) =>
          i === scores.length - 1 ? 'rgba(245,158,11,0.7)' : 'rgba(168,85,247,0.55)'),
        borderColor: scores.map((_, i) =>
          i === scores.length - 1 ? '#f59e0b' : '#a855f7'),
        borderWidth: 1.5,
        borderRadius: 4,
      }]
    },
    options: {
      responsive: true,
      plugins: {
        legend: { display: false },
        tooltip: { callbacks: { label: ctx => ` Score: ${fmtComma(ctx.raw)}` } }
      },
      scales: {
        y: {
          grid: { color: 'rgba(255,255,255,0.05)' },
          ticks: { callback: v => fmtNum(v) }
        },
        x: { grid: { display: false } }
      }
    }
  });
}

// ── MEMBER PERFORMANCE TAB ────────────────────────────────────────────────────

function renderMembersTab() {
  // Build a unique sorted member list from all festivals
  const memberSet = new Map();
  festivals.forEach(f => {
    (f.players || []).forEach(p => {
      if (!memberSet.has(p.name)) {
        const allScores = festivals
          .map(ff => (ff.players || []).find(x => x.name === p.name)?.score ?? 0);
        memberSet.set(p.name, allScores);
      }
    });
  });

  // Render quick-pick chips (sorted by latest festival score desc)
  const members = [...memberSet.entries()].sort((a, b) => {
    const aLast = a[1][a[1].length - 1] || 0;
    const bLast = b[1][b[1].length - 1] || 0;
    return bLast - aLast;
  });

  const chipsEl = document.getElementById('member-list-quick');
  chipsEl.innerHTML = members.slice(0, 30).map(([name]) =>
    `<span class="member-chip" onclick="lookupMember('${name.replace(/'/g,"\\'")}')">👤 ${name}</span>`
  ).join('');
}

document.getElementById('member-search-btn').addEventListener('click', () => {
  const q = document.getElementById('member-search-input').value.trim();
  if (q) lookupMember(q);
});
document.getElementById('member-search-input').addEventListener('keydown', e => {
  if (e.key === 'Enter') document.getElementById('member-search-btn').click();
});

function lookupMember(nameQuery) {
  const q = nameQuery.toLowerCase();
  // Find canonical name
  let canonical = null;
  for (const f of festivals) {
    const hit = (f.players || []).find(p => p.name.toLowerCase().includes(q));
    if (hit) { canonical = hit.name; break; }
  }

  if (!canonical) {
    document.getElementById('member-result').style.display = 'none';
    document.getElementById('member-list-quick').innerHTML =
      `<div class="error-state" style="margin-top:0.5rem">❌ Member not found: <strong>${nameQuery}</strong></div>`;
    return;
  }

  // Collect scores per festival
  const labels = [];
  const scores = [];
  const rows   = [];

  festivals.forEach(f => {
    const p = (f.players || []).find(x => x.name === canonical);
    labels.push(shortDate(f.date));
    const score = p ? p.score : 0;
    scores.push(score);
    rows.push({ date: f.date, score, completed: p?.completed ?? '—', total: p?.total ?? '—', bonus: p?.bonus ?? false, found: !!p });
  });

  const best  = Math.max(...scores);
  const avg   = scores.length ? Math.round(scores.reduce((a,b)=>a+b,0)/scores.length) : 0;
  const passed = scores.filter(s => s >= FESTIVAL_MIN).length;

  // Summary box
  document.getElementById('member-summary-box').innerHTML = `
    <h2>👤 ${canonical}</h2>
    <div class="meta-row">
      <div class="meta-item">🎪 Festivals: <strong>${scores.length}</strong></div>
      <div class="meta-item">🏆 Best: <strong>${fmtComma(best)}</strong></div>
      <div class="meta-item">📊 Avg: <strong>${fmtComma(avg)}</strong></div>
      <div class="meta-item met-yes">✅ Passed min: <strong>${passed}/${scores.length}</strong></div>
    </div>`;

  document.getElementById('member-result').style.display = '';

  // Charts
  buildMemberLineChart(labels, scores, canonical);
  buildMemberBarChart(labels, scores, canonical);

  // Table
  const tbody = document.getElementById('member-tbody');
  tbody.innerHTML = [...rows].reverse().map(r => {
    const met    = r.score >= FESTIVAL_MIN;
    const isBest = r.score === best && best > 0;
    const cls    = isBest ? 'row-best' : (met ? 'row-pass' : 'row-fail');
    return `<tr class="${cls}">
      <td>${fullDate(r.date)}</td>
      <td class="right"><strong>${r.found ? fmtComma(r.score) : '—'}</strong></td>
      <td class="center ${met?'met-yes':'met-no'}">${r.found ? (met ? '✅ YES' : '❌ NO') : '—'}</td>
      <td class="center">${r.found ? r.completed+'/'+r.total : '—'}</td>
      <td class="center">${r.found ? (r.bonus ? '✅' : '—') : '—'}</td>
    </tr>`;
  }).join('');
}

function buildMemberLineChart(labels, scores, name) {
  destroyChart(chartMemberLine);
  const ctx = document.getElementById('chart-member-line').getContext('2d');
  chartMemberLine = new Chart(ctx, {
    type: 'line',
    data: {
      labels,
      datasets: [
        {
          label: name,
          data: scores,
          borderColor: '#a855f7',
          backgroundColor: 'rgba(168,85,247,0.08)',
          pointBackgroundColor: scores.map(s =>
            s >= FESTIVAL_MIN ? '#22c55e' : '#ef4444'),
          pointRadius: 6,
          tension: 0.3,
          fill: true,
        },
        {
          label: `Min. (${fmtComma(FESTIVAL_MIN)})`,
          data: new Array(labels.length).fill(FESTIVAL_MIN),
          borderColor: 'rgba(239,68,68,0.6)',
          borderDash: [6, 4],
          borderWidth: 1.5,
          pointRadius: 0,
          fill: false,
        }
      ]
    },
    options: {
      responsive: true,
      interaction: { mode: 'index', intersect: false },
      plugins: {
        tooltip: { callbacks: { label: ctx => ` ${ctx.dataset.label}: ${fmtComma(ctx.raw)}` } }
      },
      scales: {
        y: { grid: { color: 'rgba(255,255,255,0.05)' }, ticks: { callback: v => fmtNum(v) } },
        x: { grid: { color: 'rgba(255,255,255,0.04)' } }
      }
    }
  });
}

function buildMemberBarChart(labels, scores, name) {
  destroyChart(chartMemberBar);
  const best = Math.max(...scores);
  const ctx = document.getElementById('chart-member-bar').getContext('2d');
  chartMemberBar = new Chart(ctx, {
    type: 'bar',
    data: {
      labels,
      datasets: [{
        label: 'Score',
        data: scores,
        backgroundColor: scores.map((s, i) => {
          if (s === best && best > 0) return 'rgba(245,158,11,0.7)';
          if (s >= FESTIVAL_MIN)      return 'rgba(34,197,94,0.55)';
          return 'rgba(239,68,68,0.5)';
        }),
        borderColor: scores.map((s, i) => {
          if (s === best && best > 0) return '#f59e0b';
          if (s >= FESTIVAL_MIN)      return '#22c55e';
          return '#ef4444';
        }),
        borderWidth: 1.5,
        borderRadius: 4,
      }]
    },
    options: {
      responsive: true,
      plugins: {
        legend: { display: false },
        tooltip: { callbacks: { label: ctx => ` Score: ${fmtComma(ctx.raw)}` } }
      },
      scales: {
        y: {
          grid: { color: 'rgba(255,255,255,0.05)' },
          ticks: { callback: v => fmtNum(v) }
        },
        x: { grid: { display: false } }
      }
    }
  });
}

// ── Start ─────────────────────────────────────────────────────────────────────
init();
