/* festival.js — Guild Festival dashboard
 *
 * Data source: ./data/festival.json
 * Structure (generated by publish_website.py):
 * [
 *   {
 *     "date": "2026-03-30",
 *     "filename": "...",
 *     "summary": { "total_players": N, "completed_bonus": N, "total_score": N },
 *     "players": [ { "name", "score", "completed", "total", "bonus" }, ... ]
 *   },
 *   ...
 * ]
 */

// FESTIVAL_MIN is injected from the data (summary.festival_min_score) so it
// stays in sync with config.json without re-deploying JS.
// It is initialised to the fallback value and updated after the data loads.
let FESTIVAL_MIN = 3100;
const _inPages = window.location.pathname.includes('/pages/');
const DATA_URL     = (_inPages ? '../data/' : './data/') + 'festival.json';

// Chart.js theme utilities
const _getThemeColor = (variable, fallback) => {
  const val = getComputedStyle(document.documentElement).getPropertyValue(variable).trim();
  return val || fallback;
};

const updateChartDefaults = () => {
  if (window.Chart) {
    Chart.defaults.color           = _getThemeColor('--text-secondary', '#8b949e');
    Chart.defaults.borderColor     = _getThemeColor('--border', '#30363d');
    Chart.defaults.font.family     = "'Inter', -apple-system, sans-serif";
  }
};
updateChartDefaults();

// Dynamic theme change updates for active Chart.js instances in festival page
window.addEventListener('themechanged', () => {
  updateChartDefaults();
  const newTextColor = _getThemeColor('--text-muted', '#6e7681');
  const newGridColor = _getThemeColor('--border', '#30363d');
  const newLegendColor = _getThemeColor('--text-secondary', '#8b949e');
  
  const instances = Chart.instances;
  const chartList = Array.isArray(instances) ? instances : Object.values(instances || {});
  
  chartList.forEach(chart => {
    // Update datasets dynamically
    if (chart.data && chart.data.datasets) {
      chart.data.datasets.forEach(dataset => {
        if (dataset._cssBorderVar) {
          const color = _getThemeColor(dataset._cssBorderVar);
          dataset.borderColor = color;
          dataset.pointBorderColor = color;
          dataset.pointHoverBackgroundColor = color;
          
          if (dataset._cssBgVar) {
            dataset.backgroundColor = color + '12'; // translucent fill
          }
        }
      });
    }
    
    if (chart.options.scales) {
      if (chart.options.scales.x) {
        if (chart.options.scales.x.ticks) {
          chart.options.scales.x.ticks.color = newTextColor;
        }
        if (chart.options.scales.x.grid) {
          chart.options.scales.x.grid.color = newGridColor;
        }
      }
      if (chart.options.scales.y) {
        if (chart.options.scales.y.ticks) {
          chart.options.scales.y.ticks.color = newTextColor;
        }
        if (chart.options.scales.y.grid) {
          chart.options.scales.y.grid.color = newGridColor;
        }
        if (chart.options.scales.y.title) {
          chart.options.scales.y.title.color = newTextColor;
        }
      }
    }
    if (chart.options.plugins && chart.options.plugins.legend && chart.options.plugins.legend.labels) {
      chart.options.plugins.legend.labels.color = newLegendColor;
    }
    chart.update();
  });
});

// ── State ───────────────────────────────────────────────────────────────────
let festivals    = [];   // sorted oldest → newest
let activeTab    = 'history';
let selectedFest = null; // currently drilled-in festival
let chartHistLine, chartHistBar, chartMemberLine, chartMemberBar;

// ── Utilities ────────────────────────────────────────────────────────────────

const fmtNum = n => (n >= 1_000_000 ? (n/1_000_000).toFixed(1)+'M'
                   : n >= 1_000     ? (n/1_000).toFixed(1)+'K'
                   : String(n));

const fmtComma = n => Number(n).toLocaleString(window.i18n?.currentLang || 'en');

const shortDate = d => {
  try {
    const dt = new Date(d + 'T00:00:00');
    return dt.toLocaleDateString(window.i18n?.currentLang || 'en', {month:'short', day:'numeric'});
  } catch { return d.slice(5,10); }
};

const fullDate = d => {
  try {
    const dt = new Date(d + 'T00:00:00');
    return dt.toLocaleDateString(window.i18n?.currentLang || 'en', {year:'numeric', month:'long', day:'numeric'});
  } catch { return d; }
};

function destroyChart(c) { if (c) { try { c.destroy(); } catch {} } }

// ── Fetch ────────────────────────────────────────────────────────────────────

async function loadData() {
  const resp = await fetch(DATA_URL + '?v=' + Date.now());
  if (!resp.ok) throw new Error(`HTTP ${resp.status}`);
  return resp.json();
}

// ── Init ─────────────────────────────────────────────────────────────────────

async function init() {
  try {
    const raw = await loadData();
    // Sort oldest → newest
    festivals = [...raw].sort((a, b) => (a.date > b.date ? 1 : -1));
    // Sync FESTIVAL_MIN from the most recent festival's config field
    if (festivals.length > 0) {
      const lastSummary = festivals[festivals.length - 1].summary || {};
      FESTIVAL_MIN = lastSummary.festival_min_score || FESTIVAL_MIN;
    }
    renderHistoryTab();
  } catch (err) {
    document.getElementById('festival-list').innerHTML =
      `<div class="error-state">⚠️ ${t('error_loading')}: ${err.message}</div>`;
  }
}

document.addEventListener('DOMContentLoaded', () => {
  if (window.location.pathname.split('/').pop() !== 'festival.html') return;
  // Wait for i18n to be ready before first render
  const checkI18n = setInterval(() => {
    if (window.i18n && Object.keys(window.i18n.data).length > 0) {
      clearInterval(checkI18n);
      init();
    }
  }, 50);

  // Re-render when language changes
  window.addEventListener('languageChanged', () => {
    renderHistoryTab();
  });
});

// ── HISTORY TAB ──────────────────────────────────────────────────────────────


function renderHistoryTab() {
  if (!festivals.length) {
    document.getElementById('festival-list').innerHTML =
      `<div class="empty-state"><div class="empty-icon">🎪</div><h3>${t('no_fest_data')}</h3></div>`;
    return;
  }

  let sumAvgScore = 0; let sumPass = 0; let sumFail = 0; let sumBonus = 0;
  festivals.forEach(f => {
     const pLen = f.summary.total_players || 1;
     sumAvgScore += Math.round(f.summary.total_score / pLen);
     sumPass += f.summary.passed_min;
     sumFail += f.summary.failed_min;
     sumBonus += f.summary.completed_bonus || 0;
  });
  const n = festivals.length;
  document.getElementById('stat-festivals').textContent    = n;
  document.getElementById('stat-avg-score').textContent    = fmtNum(Math.round(sumAvgScore / n));
  document.getElementById('stat-avg-pass').textContent     = Math.round(sumPass / n);
  document.getElementById('stat-avg-fail').textContent     = Math.round(sumFail / n);
  document.getElementById('stat-avg-bonus').textContent    = Math.round(sumBonus / n);
  document.getElementById('festival-count-badge').textContent = `${n} ${t('events_count')}`;

  buildHistoryCharts();
  renderFestivalList(festivals);
}

function renderFestivalList(list) {
  const el = document.getElementById('festival-list');
  if (!list.length) {
    el.innerHTML = `<div class="empty-state"><div class="empty-icon">🔍</div><h3>${t('no_results')}</h3></div>`;
    return;
  }

  // Render newest first in the card list
  const sorted = [...list].reverse();

  el.innerHTML = `<div class="session-list" style="padding:1.5rem">` +
    sorted.map((f, i) => {
      const s       = f.summary;
      const players = f.players || [];
      const passed  = players.filter(p => p.score >= FESTIVAL_MIN).length;
      const pct     = players.length ? Math.round(passed / players.length * 100) : 0;
      const isLatest = f === festivals[festivals.length - 1];

      return `
      <div class="session-card" data-date="${f.date}" onclick="openFestivalDetail('${f.date}')">
        <div class="session-title">
          🎪 ${fullDate(f.date)}
          ${isLatest ? `<span class="badge" style="font-size:0.7rem;background:rgba(var(--accent-rgb),0.12);color:var(--accent);border-color:rgba(var(--accent-rgb),0.25)">${t('latest')}</span>` : ''}
        </div>
        <div class="session-meta">
          <div class="session-row">
            <span>🏆 ${t('total_score')}</span>
            <span class="val">${fmtNum(s.total_score)}</span>
          </div>
          <div class="session-row">
            <span>👥 ${t('players')}</span>
            <span class="val">${s.total_players}</span>
          </div>
          <div class="session-row">
            <span>✅ ${t('bonus_completed')}</span>
            <span class="val">${s.completed_bonus}</span>
          </div>
          <div class="session-row" style="margin-top:4px">
            <span>${t('min_met')} (≥${fmtComma(FESTIVAL_MIN)})</span>
            <span class="val" style="color:${pct>=80?'var(--festival-pass)':pct>=50?'var(--accent-yellow)':'var(--festival-fail)'}">${passed}/${s.total_players} (${pct}%)</span>
          </div>
          <div class="pass-bar-wrap" style="margin-top:6px">
            <div class="pass-bar-track" style="flex:1">
              <div class="pass-bar-fill" style="width:${pct}%"></div>
            </div>
            <span style="color:var(--text-muted);font-size:0.78rem;min-width:34px">${pct}%</span>
          </div>
        </div>
        <div class="view-btn">${t('view_details')}</div>
      </div>`;
    }).join('') + '</div>';
}

// Search filter
document.getElementById('search-festival').addEventListener('input', e => {
  const q = e.target.value.toLowerCase().trim();
  const filtered = q ? festivals.filter(f => f.date.includes(q) || shortDate(f.date).toLowerCase().includes(q)) : festivals;
  renderFestivalList(filtered);
});

// ── FESTIVAL DETAIL ───────────────────────────────────────────────────────────

function openFestivalDetail(date) {
  const f = festivals.find(x => x.date === date);
  if (!f) return;
  selectedFest = f;

  document.getElementById('festival-list').style.display    = 'none';
  document.getElementById('festival-detail').style.display  = '';
  document.getElementById('search-festival').parentElement.parentElement.style.display = 'none';
  // Hide chart cards while in detail
  document.querySelectorAll('#tab-history-content .card:not(#festival-detail .card)').forEach(c => c.style.display='none');
  document.getElementById('festival-stats').style.display   = 'none';

  const s       = f.summary;
  const players = [...(f.players || [])].sort((a, b) => b.score - a.score);
  const passed  = players.filter(p => p.score >= FESTIVAL_MIN).length;
  const pct     = players.length ? Math.round(passed / players.length * 100) : 0;

  document.getElementById('detail-title').textContent = fullDate(f.date);

  // Detail summary box
  document.getElementById('detail-summary-box').innerHTML = `
    <h2>${fullDate(f.date)}</h2>
    <div class="festival-score-big">${fmtNum(s.total_score)}</div>
    <div class="meta-row" style="margin-top:0.8rem">
      <div class="meta-item">👥 <strong>${s.total_players}</strong> ${t('players')}</div>
      <div class="meta-item">✅ ${t('bonus')}: <strong>${s.completed_bonus}</strong></div>
      <div class="meta-item met-yes">✔ ${t('min_met')}: <strong>${passed} (${pct}%)</strong></div>
      <div class="meta-item met-no">✖ ${t('miss')}: <strong>${players.length - passed}</strong></div>
    </div>
    <div class="pass-bar-wrap" style="margin-top:10px">
      <span style="font-size:0.8rem;color:var(--text-muted)">${t('min_compliance')}</span>
      <div class="pass-bar-track" style="flex:1">
        <div class="pass-bar-fill" style="width:${pct}%"></div>
      </div>
      <span style="font-size:0.8rem;color:var(--text-muted)">${pct}%</span>
    </div>`;

  renderDetailTable(players);

  document.getElementById('search-detail').addEventListener('input', e => {
    const q = e.target.value.toLowerCase();
    renderDetailTable(q ? players.filter(p => p.name.toLowerCase().includes(q)) : players);
  });
}

function renderDetailTable(players) {
  const best = players.length ? Math.max(...players.map(p => p.score)) : 0;
  const tbody = document.getElementById('detail-tbody');
  tbody.innerHTML = players.map((p, i) => {
    const met   = p.score >= FESTIVAL_MIN;
    const isBest = p.score === best && best > 0;
    const cls   = isBest ? 'row-best' : (met ? 'row-pass' : 'row-fail');
    return `<tr class="${cls}">
      <td class="center" data-label="#">${i+1}</td>
      <td data-label="${t('table_player')}">${isBest ? '🥇 ' : ''}${p.name}</td>
      <td class="right" data-label="${t('score')}"><strong>${fmtNum(p.score)}</strong></td>
      <td class="center ${met?'met-yes':'met-no'}" data-label="${t('table_status')}">${met ? t('met_yes') : t('met_no')}</td>
      <td class="center" data-label="${t('bonus_completed')}">${p.completed}/${p.total}</td>
      <td class="center ${p.bonus?'met-yes':''}" data-label="${t('bonus')}">${p.bonus ? '✅' : '—'}</td>
    </tr>`;
  }).join('');
}

// Back button
document.getElementById('back-to-list').addEventListener('click', e => {
  e.preventDefault();
  document.getElementById('festival-list').style.display    = '';
  document.getElementById('festival-detail').style.display  = 'none';
  document.getElementById('search-festival').parentElement.parentElement.style.display = '';
  document.querySelectorAll('#tab-history-content .card').forEach(c => c.style.display='');
  document.getElementById('festival-stats').style.display   = '';
  selectedFest = null;
});


// ── HISTORY CHARTS ────────────────────────────────────────────────────────────
function buildHistoryCharts() {
  destroyChart(chartHistLine);
  destroyChart(chartHistBar);

  const labels    = festivals.map(f => shortDate(f.date));
  const avgScores = festivals.map(f => Math.round(f.summary.total_score / (f.summary.total_players || 1)));
  const passed    = festivals.map(f => f.summary.passed_min        || 0);
  const failed    = festivals.map(f => f.summary.failed_min        || 0);
  const bonus     = festivals.map(f => f.summary.completed_bonus   || 0);

  const _tip = {
    backgroundColor: _getThemeColor('--bg-secondary', 'rgba(10,12,18,0.95)'),
    titleColor: _getThemeColor('--text-primary', '#e6edf3'),
    bodyColor: _getThemeColor('--text-secondary', '#8b949e'),
    borderColor: _getThemeColor('--border', 'rgba(99,110,123,0.4)'),
    borderWidth: 1, padding: 12, cornerRadius: 10,
    titleFont: { size: 13, weight: '600' }, bodyFont: { size: 12 },
    displayColors: true, boxWidth: 8, boxHeight: 8, usePointStyle: true
  };

  const _legend = { position: 'top', labels: { usePointStyle: true, boxWidth: 10, color: _getThemeColor('--text-secondary', 'rgba(255,255,255,0.7)'), padding: 14 } };

  const _ptStyle = (color) => ({ pointRadius: 0, pointHoverRadius: 6, pointBackgroundColor: _getThemeColor('--bg-primary', '#0d1117'), pointBorderColor: color, pointBorderWidth: 2 });

  const passedColor = _getThemeColor('--accent-green', '#22c55e');
  const failedColor = _getThemeColor('--accent-red', '#ef4444');
  const bonusColor  = _getThemeColor('--accent', '#a855f7');
  const avgColor    = _getThemeColor('--accent-yellow', '#f59e0b');

  // ── Compliance line chart (3 toggle-able lines) ─────────────────────────────
  const ctxBar = document.getElementById('chart-history-bar').getContext('2d');
  chartHistBar = new Chart(ctxBar, {
    type: 'line',
    data: {
      labels,
      datasets: [
        { label: t('fest_part_completed'),   data: passed, borderColor: passedColor, backgroundColor: passedColor + '12',   borderWidth: 2.5, tension: 0.3, fill: false, _cssBorderVar: '--accent-green', ..._ptStyle(passedColor) },
        { label: t('fest_part_failed'),   data: failed, borderColor: failedColor, backgroundColor: failedColor + '12',   borderWidth: 2.5, tension: 0.3, fill: false, _cssBorderVar: '--accent-red', ..._ptStyle(failedColor) },
        { label: t('fest_bonus_earned'), data: bonus,  borderColor: bonusColor, backgroundColor: bonusColor + '12',  borderWidth: 2.5, tension: 0.3, fill: false, borderDash: [5,3], _cssBorderVar: '--accent', ..._ptStyle(bonusColor) }
      ]
    },
    options: {
      responsive: true, maintainAspectRatio: false,
      interaction: { mode: 'index', intersect: false },
      plugins: { legend: _legend, tooltip: _tip },
      scales: {
        x: { grid: { display: false }, ticks: { color: _getThemeColor('--text-secondary', '#8b949e') } },
        y: {
          grid: { color: _getThemeColor('--border', 'rgba(255,255,255,0.05)') },
          title: { display: true, text: t('players'), color: _getThemeColor('--text-secondary', 'rgba(255,255,255,0.5)') },
          beginAtZero: true,
          ticks: { color: _getThemeColor('--text-secondary', '#8b949e') }
        }
      }
    }
  });

  // ── Average points line chart ────────────────────────────────────────────────
  const ctxLine = document.getElementById('chart-history-line').getContext('2d');
  chartHistLine = new Chart(ctxLine, {
    type: 'line',
    data: {
      labels,
      datasets: [{
        label: t('avg_pts_player_ax'),
        data: avgScores,
        borderColor: avgColor,
        backgroundColor: festivals.length === 1 ? avgColor + 'aa' : avgColor + '12',
        borderWidth: 2.5, tension: 0.3,
        fill: true,
        _cssBorderVar: '--accent-yellow',
        _cssBgVar: '--accent-yellow',
        ..._ptStyle(avgColor)
      }]
    },
    options: {
      responsive: true, maintainAspectRatio: false,
      interaction: { mode: 'index', intersect: false },
      plugins: {
        legend: { position: 'top', labels: { usePointStyle: true, boxWidth: 10, color: _getThemeColor('--text-secondary', 'rgba(255,255,255,0.7)') } },
        tooltip: _tip
      },
      scales: {
        x: { grid: { display: false }, ticks: { color: _getThemeColor('--text-secondary', '#8b949e') } },
        y: {
          grid: { color: _getThemeColor('--border', 'rgba(255,255,255,0.05)') },
          title: { display: true, text: t('avg_pts_player_ax'), color: _getThemeColor('--text-secondary', 'rgba(255,255,255,0.5)') },
          beginAtZero: false,
          ticks: { color: _getThemeColor('--text-secondary', '#8b949e') }
        }
      }
    }
  });
}

// ── Start ─────────────────────────────────────────────────────────────────────
// init() called by DOMContentLoaded above

// Re-render when language changes
window.addEventListener('languageChanged', () => {
  if (selectedFest) {
    openFestivalDetail(selectedFest.date);
  } else {
    renderHistoryTab();
  }
});


